c
c --- common blocks related to nesting
c
      c o m m o n /nest1/
     .  depths_o(idm_o,jdm_o),
     .  temp_ow1(nbz,jdm,kdm),temp_ow2(nbz,jdm,kdm),
     .  temp_oe1(nbz,jdm,kdm),temp_oe2(nbz,jdm,kdm),
     .  temp_os1(idm,nbz,kdm),temp_os2(idm,nbz,kdm),
     .  temp_on1(idm,nbz,kdm),temp_on2(idm,nbz,kdm),
     .  saln_ow1(nbz,jdm,kdm),saln_ow2(nbz,jdm,kdm),
     .  saln_oe1(nbz,jdm,kdm),saln_oe2(nbz,jdm,kdm),
     .  saln_os1(idm,nbz,kdm),saln_os2(idm,nbz,kdm),
     .  saln_on1(idm,nbz,kdm),saln_on2(idm,nbz,kdm),
     .  utot_ow1(nbz,jdm,kdm),utot_ow2(nbz,jdm,kdm),
     .  utot_oe1(nbz,jdm,kdm),utot_oe2(nbz,jdm,kdm),
     .  utot_os1(idm,nbz,kdm),utot_os2(idm,nbz,kdm),
     .  utot_on1(idm,nbz,kdm),utot_on2(idm,nbz,kdm),
     .  vtot_ow1(nbz,jdm,kdm),vtot_ow2(nbz,jdm,kdm),
     .  vtot_oe1(nbz,jdm,kdm),vtot_oe2(nbz,jdm,kdm),
     .  vtot_os1(idm,nbz,kdm),vtot_os2(idm,nbz,kdm),
     .  vtot_on1(idm,nbz,kdm),vtot_on2(idm,nbz,kdm),
     .  dp_ow1(nbz,jdm,kdm+1),dp_ow2(nbz,jdm,kdm+1),
     .  dp_oe1(nbz,jdm,kdm+1),dp_oe2(nbz,jdm,kdm+1),
     .  dp_os1(idm,nbz,kdm+1),dp_os2(idm,nbz,kdm+1),
     .  dp_on1(idm,nbz,kdm+1),dp_on2(idm,nbz,kdm+1),
     .  ficem_ow1(nbz,jdm),ficem_ow2(nbz,jdm),
     .  ficem_oe1(nbz,jdm),ficem_oe2(nbz,jdm),
     .  ficem_os1(idm,nbz),ficem_os2(idm,nbz),
     .  ficem_on1(idm,nbz),ficem_on2(idm,nbz),
     .  hicem_ow1(nbz,jdm),hicem_ow2(nbz,jdm),
     .  hicem_oe1(nbz,jdm),hicem_oe2(nbz,jdm),
     .  hicem_os1(idm,nbz),hicem_os2(idm,nbz),
     .  hicem_on1(idm,nbz),hicem_on2(idm,nbz),
     .  hsnwm_ow1(nbz,jdm),hsnwm_ow2(nbz,jdm),
     .  hsnwm_oe1(nbz,jdm),hsnwm_oe2(nbz,jdm),
     .  hsnwm_os1(idm,nbz),hsnwm_os2(idm,nbz),
     .  hsnwm_on1(idm,nbz),hsnwm_on2(idm,nbz),
     .  iagem_ow1(nbz,jdm),iagem_ow2(nbz,jdm),
     .  iagem_oe1(nbz,jdm),iagem_oe2(nbz,jdm),
     .  iagem_os1(idm,nbz),iagem_os2(idm,nbz),
     .  iagem_on1(idm,nbz),iagem_on2(idm,nbz),
     .  pb_ow1(2,jdm),pb_ow2(2,jdm),
     .  pb_oe1(2,jdm),pb_oe2(2,jdm),
     .  pb_os1(idm,2),pb_os2(idm,2),
     .  pb_on1(idm,2),pb_on2(idm,2),
     .  ub_ow1(jdm),ub_ow2(jdm),
     .  ub_oe1(jdm),ub_oe2(jdm),
     .  ub_os1(idm),ub_os2(idm),
     .  ub_on1(idm),ub_on2(idm),
     .  vb_ow1(jdm),vb_ow2(jdm),
     .  vb_oe1(jdm),vb_oe2(jdm),
     .  vb_os1(idm),vb_os2(idm),
     .  vb_on1(idm),vb_on2(idm),
     .  wnst(nbz)
c
      real depths_o,
     .     temp_ow1,temp_ow2,temp_oe1,temp_oe2,
     .     temp_os1,temp_os2,temp_on1,temp_on2,
     .     saln_ow1,saln_ow2,saln_oe1,saln_oe2,
     .     saln_os1,saln_os2,saln_on1,saln_on2,
     .     utot_ow1,utot_ow2,utot_oe1,utot_oe2,
     .     utot_os1,utot_os2,utot_on1,utot_on2,
     .     vtot_ow1,vtot_ow2,vtot_oe1,vtot_oe2,
     .     vtot_os1,vtot_os2,vtot_on1,vtot_on2,
     .     dp_ow1,dp_ow2,dp_oe1,dp_oe2,
     .     dp_os1,dp_os2,dp_on1,dp_on2,
     .     ficem_ow1,ficem_ow2,ficem_oe1,ficem_oe2,
     .     ficem_os1,ficem_os2,ficem_on1,ficem_on2,
     .     hicem_ow1,hicem_ow2,hicem_oe1,hicem_oe2,
     .     hicem_os1,hicem_os2,hicem_on1,hicem_on2,
     .     hsnwm_ow1,hsnwm_ow2,hsnwm_oe1,hsnwm_oe2,
     .     hsnwm_os1,hsnwm_os2,hsnwm_on1,hsnwm_on2,
     .     iagem_ow1,iagem_ow2,iagem_oe1,iagem_oe2,
     .     iagem_os1,iagem_os2,iagem_on1,iagem_on2,
     .     pb_ow1,pb_ow2,pb_oe1,pb_oe2,pb_os1,pb_os2,pb_on1,pb_on2,
     .     ub_ow1,ub_ow2,ub_oe1,ub_oe2,ub_os1,ub_os2,ub_on1,ub_on2,
     .     vb_ow1,vb_ow2,vb_oe1,vb_oe2,vb_os1,vb_os2,vb_on1,vb_on2,
     .     wnst
c
      c o m m o n /nest2/
     . otr2dfq,otr3dfq,nyrotr,nmnotr,ndyotr,lptotr,
     . nst21,nst22,nst31,nst32,
     . otr2dmon,otr3dmon,rngotr,pthotr
c
      real otr2dfq,otr3dfq
      integer nyrotr,nmnotr,ndyotr,lptotr,nst21,nst22,nst31,nst32
      logical otr2dmon,otr3dmon
      character rngotr*3,pthotr*80
